### ISSUE TITLE
🐞 - Redundant nullish coalescing operator

### ISSUE THREAD

**Issue by hakimio** [taiga-family/editor#1324]
### Description

Following line has redundant nullish coalescing operator since the left side of the operator will never be null:
https://github.com/taiga-family/editor/blob/6a5ebebe71ca2922cc8b2b526cc77dfdbe1ada24/projects/editor/src/components/toolbar-tools/details/details-remove/details-remove.component.ts#L48

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Editor is typed to be possibly `null`. While technically this will never happen in this particular place, the only way to tell TS that is to save `editor` to local `const` so that by the time `map` callback is executed TS would be sure about the type. I don't think it's worth it since nullish coalescing operator is now natively supported by all the browsers Taiga UI supports so it will not add bloat to the bundle by transpilling.

**Comment by waterplea** [comment]
Oh snap, sorry, I misread the line 😄 Yea, you're right. Feel free to send a PR.

**Comment by hakimio** [comment]
Reopen maybe?
